name: Building Docker images and pushing to ECR
on:
  push:
    branches:
      - main

jobs:
  build and push:
    runs_on: ubuntu-latest
  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ secret.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secret.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secret.AWS_REGION }}

  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v2

  - name: Build, Push and tag image to ECR
    env: 
      ECR_REPOSITORY: myapp
      IMAGE_TAG: ${{ github.sha }}
    run: 
      docker build -t $ECR_REPOSITORY:latest .
      docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
      docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
      docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
      docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
